flathub/org.telegram.desktop

- org.telegram.desktop.json
Add libnotify and required dbus access.
Fixes: #1
> Fix native notifications

- org.telegram.desktop.json
Reverts flathub/org.telegram.desktop#106
> Revert "Drop bundled ffmpeg"

- .gitmodules
- org.telegram.desktop.json
This includes changes from 1.9.10-11 betas.
> Update to 1.9.13

- org.telegram.desktop.json
- patch/telegram-appdata-launchable.patch
Hopefully this fixes #143, and closes #137
> Add <launchable> tag to appdata

- org.telegram.desktop.json
We really need to automate this somehow.
> Update to 1.9.16 beta

- org.telegram.desktop.json
> Update to 2.0.0

- org.telegram.desktop.json
Wish this could be automated somehow.
Closes #158
> Update to 2.1.0

- org.telegram.desktop.json
> Use new DESKTOP_APP_USE_PACKAGED_LAZY to reduce maintenance complexity

- org.telegram.desktop.json
> Update to 2.1.7

- org.telegram.desktop.json
> Update to 2.1.11

- org.telegram.desktop.json
> Update to 2.1.12

- org.telegram.desktop.json
> Update to 2.1.13

- org.telegram.desktop.json
> Update to 2.2.0

- org.telegram.desktop.json
> Runtime: update to version 5.15

- org.telegram.desktop.json
- telegram-wrapper.sh
> Update to 2.4.10 beta

- org.telegram.desktop.json
- patches/cmake-find-system-xcb.patch
> Update to 2.4.13 beta

- flathub.json
- org.telegram.desktop.json
- patches/tg_owt-add-missing-arm-sources.patch
> Fix ARM build

- org.telegram.desktop.json
Checking build with some optimizations enabled (not sure how else it is possible to do locally without owning an ARM host)...
> Update tg_owt for more ARM optimizations

- org.telegram.desktop.yml
This should provide more synchronized cflags across modules
> Migrate to CMAKE_BUILD_TYPE=None

- org.telegram.desktop.yml
Or Qt will fallback to some dummy cursor theme not having even resize cursors
> Create 'default' cursor theme

- org.telegram.desktop.yml
Adwaita adds 20 MB to the package size for no gain
> Use DMZ cursor theme as default cursor theme

- org.telegram.desktop.yml
This is hopefully the latest improvement we have to get from dev branch
> Get better support for portal's notification default action

- org.telegram.desktop.yml
> Update runtime to 22.08

- org.telegram.desktop.yml
statx option was removed and so none of those three options have sense now
> Remove qtbase options doing nothing now

- org.telegram.desktop.yml
Notification portal seem to work way worse
> Restore org.freedesktop.Notifications permission
