flathub/org.telegram.desktop

Avoid-depending-on-static-libraries.patch, org.telegram.desktop.json
And an update for the Qt version currently in the SDK.
https://github.com/flathub/shared-modules/pull/37
=> Use dbus-glib 0.110 from shared-modules

org.telegram.desktop.json
Telegram is now based on the KDE 5.12/fd.o 18.08 runtime, which already implicitly sets these flags.
=> Remove obsolete build flags

org.telegram.desktop.json
Telegram downloads media to `$XDG_DOWNLOAD_DIR/Telegram Desktop` by default, when viewed in the client. File dialog (and thus portal) isn't involved in it, so, without this permission, downloaded files are stored inside sandbox.
=> Add xdg-download permission

org.telegram.desktop.json
Same result, cleaner solution. Fixes #57.
http://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access
=> Use /var/tmp instead of a wrapper script

org.telegram.desktop.json
This is required for Fcitx users for characters such as backtick.
Closes: #11
Ref: flatpak/flatpak#2031
=> add --talk-name=org.freedesktop.portal.Fcitx

org.telegram.desktop.json, patch/telegram-fontconfig-use-host-fonts.patch
This resolves issues with flatpak where CJK cannot be found on the host.
Note that users that have already executed telegram will need to run `sudo rm ~/.var/app/org.telegram.desktop/data/TelegramDesktop/tdata/fc-custom-1.conf` to clear the existing "wrong" font config file. Then when Telegram is started with this patch it will install the correct fc-custom file.
Also note that the Resources folder in telegram appears to be split into a submodule in future releases, so this patch will need to be instead run against the submodule for the future 1.9.X series ( eg fc-custom.conf has moved from here https://github.com/telegramdesktop/tdesktop/blob/v1.8.15/Telegram/Resources/fc-custom.conf to here https://github.com/desktop-app/lib_ui/blob/master/qt_conf/fc-custom.conf )
I also wonder if we …
=> fc-custom.conf: add /run/host/fonts to fontconfig search path

org.telegram.desktop.json
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/2046 was merged, enabling opus muxer in runtime ffmpeg, so audio recording in Telegram shouldn't break.
Follow-up for #106
=> Drop bundled ffmpeg (second try)

.gitmodules, org.telegram.desktop.json
AppIndicator was replaced with dbusmenu-qt (present in the runtime), so we don't need libappindicator and dbus-glib anymore.
=> Drop shared-modules

org.telegram.desktop.json, telegram-wrapper.sh
Telegram should work fine now on other wayland DEs. Testing wanted.
Partially fixes #170.
=> Force xcb platform only on Gnome

org.telegram.desktop.json, telegram-wrapper.sh
This effectively reverts #163
It seems like running Telegram with XWayland on Gnome started to cause more problems than it used to solve, as reported in #194 #193 #191.
Also it appears that autostarted Telegram didn't use the wrapper at all.
=> Don't force XWayland

org.telegram.desktop.json
Now tg_owt is installable, so we don't need to pass its build-dir between modules anymore.
=> Install tg_owt

org.telegram.desktop.json
Upstream now builds Qt with mozjpeg, we can just put mozjpeg in bundle so runtime Qt will use it, thanks to compatible ABI in mozjpeg.
=> Switch to mozjpeg

org.telegram.desktop.json
tdesktop and tg_owt aren't compatible with them
Fixes #234
=> Disable GLIBCXX assertions

org.telegram.desktop.yml
Latest Telegram update now has support for sharing screen (https://telegram.org/blog/group-video-calls) for it to work on the flatpak it would require to have access to PipeWire.
=> Give access to PipeWire to be able to share screen

org.telegram.desktop.yml, patches/lib_webview/0001-Use-webkitgtk-without-its-headers.patch
The `org.telegram.desktop.webview` extension flatpak will be submitted to Flathub soon, changes need to land on the app side first for the extension to be buildable.
=> WebKitGTK is moving to an extension

org.telegram.desktop.yml
Looks like libde265 ends with .so
=> Partially revert latest commit

org.telegram.desktop.yml
Since migration to Qt 6, people periodically creating issues about incorrect single instance check in flatpak. This goes from the fact Qt 6 does permission checks on the XDG_RUNTIME_DIR and there's no easy way to work around that, so declare we don't support those flatpak versions. Specifying the version that added shared /tmp support.
=> Specify minimum flatpak version

org.telegram.desktop.yml
Qt's default path is good, we just need to ensure it's not overridable
=> Switch QT_PLUGIN_PATH to unset-env

org.telegram.desktop.yml
PulseAudio shouldn't be any worse but is considered safer
=> Remove PipeWire permission

org.telegram.desktop.yml
Download repository url has moved
refer: https://lists.boost.org/Archives/boost/2024/05/256914.php
=> update boost url

org.telegram.desktop.yml
This reverts commit 5cc96301888e190b2e41d9fb93a4f84aea1e4dce.
=> Revert "Have less debug info on aarch64 to avoid OOM build failures"
